package model;

public enum Permission {
    LOOK_CUSTOMERS, LOOK_GUARDS, LOOK_HOMEOWNERS, LOOK_VISITORS, LOOK_RESIDENTS, LOOK_REGISTRY,
    CRUD_CUSTOMERS, CRUD_GUARDS, CRUD_HOMEOWNERS, CRUD_VISITORS, CRUD_RESIDENTS
}

